#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 143
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_type = 3,
  anon_sym_decl = 4,
  anon_sym_rule = 5,
  anon_sym_extractor = 6,
  anon_sym_extern = 7,
  anon_sym_RPAREN = 8,
  anon_sym_constructor = 9,
  anon_sym_infallible = 10,
  anon_sym_const = 11,
  anon_sym_primitive = 12,
  anon_sym_enum = 13,
  anon_sym_pure = 14,
  anon_sym_partial = 15,
  anon_sym__ = 16,
  anon_sym_AT = 17,
  anon_sym_and = 18,
  anon_sym_LT = 19,
  anon_sym_if_DASHlet = 20,
  anon_sym_if = 21,
  anon_sym_let = 22,
  sym_constant = 23,
  aux_sym_integer_token1 = 24,
  aux_sym_integer_token2 = 25,
  aux_sym_integer_token3 = 26,
  aux_sym_integer_token4 = 27,
  anon_sym_POUNDt = 28,
  anon_sym_POUNDf = 29,
  anon_sym_SEMI = 30,
  aux_sym_line_comment_token1 = 31,
  sym_source_file = 32,
  sym_defn = 33,
  sym_type_decl = 34,
  sym_type_value = 35,
  sym_extern = 36,
  sym_primitive = 37,
  sym_enum = 38,
  sym_enum_variant = 39,
  sym_enum_field = 40,
  sym_type = 41,
  sym_decl = 42,
  sym_rule = 43,
  sym_priority = 44,
  sym_pattern = 45,
  sym_pattern_arg = 46,
  sym_condition = 47,
  sym_if_let = 48,
  sym_if = 49,
  sym_expression = 50,
  sym_let_binding = 51,
  sym_extractor = 52,
  sym_integer = 53,
  sym_boolean = 54,
  sym_line_comment = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_enum_repeat1 = 57,
  aux_sym_enum_variant_repeat1 = 58,
  aux_sym_decl_repeat1 = 59,
  aux_sym_decl_repeat2 = 60,
  aux_sym_rule_repeat1 = 61,
  aux_sym_pattern_repeat1 = 62,
  aux_sym_pattern_repeat2 = 63,
  aux_sym_expression_repeat1 = 64,
  aux_sym_expression_repeat2 = 65,
  aux_sym_extractor_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_type] = "type",
  [anon_sym_decl] = "decl",
  [anon_sym_rule] = "rule",
  [anon_sym_extractor] = "extractor",
  [anon_sym_extern] = "extern",
  [anon_sym_RPAREN] = ")",
  [anon_sym_constructor] = "constructor",
  [anon_sym_infallible] = "infallible",
  [anon_sym_const] = "const",
  [anon_sym_primitive] = "primitive",
  [anon_sym_enum] = "enum",
  [anon_sym_pure] = "pure",
  [anon_sym_partial] = "partial",
  [anon_sym__] = "_",
  [anon_sym_AT] = "@",
  [anon_sym_and] = "and",
  [anon_sym_LT] = "<",
  [anon_sym_if_DASHlet] = "if-let",
  [anon_sym_if] = "if",
  [anon_sym_let] = "let",
  [sym_constant] = "constant",
  [aux_sym_integer_token1] = "integer_token1",
  [aux_sym_integer_token2] = "integer_token2",
  [aux_sym_integer_token3] = "integer_token3",
  [aux_sym_integer_token4] = "integer_token4",
  [anon_sym_POUNDt] = "#t",
  [anon_sym_POUNDf] = "#f",
  [anon_sym_SEMI] = ";",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [sym_source_file] = "source_file",
  [sym_defn] = "defn",
  [sym_type_decl] = "type_decl",
  [sym_type_value] = "type_value",
  [sym_extern] = "extern",
  [sym_primitive] = "primitive",
  [sym_enum] = "enum",
  [sym_enum_variant] = "enum_variant",
  [sym_enum_field] = "enum_field",
  [sym_type] = "type",
  [sym_decl] = "decl",
  [sym_rule] = "rule",
  [sym_priority] = "priority",
  [sym_pattern] = "pattern",
  [sym_pattern_arg] = "pattern_arg",
  [sym_condition] = "condition",
  [sym_if_let] = "if_let",
  [sym_if] = "if",
  [sym_expression] = "expression",
  [sym_let_binding] = "let_binding",
  [sym_extractor] = "extractor",
  [sym_integer] = "integer",
  [sym_boolean] = "boolean",
  [sym_line_comment] = "line_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_enum_repeat1] = "enum_repeat1",
  [aux_sym_enum_variant_repeat1] = "enum_variant_repeat1",
  [aux_sym_decl_repeat1] = "decl_repeat1",
  [aux_sym_decl_repeat2] = "decl_repeat2",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_pattern_repeat2] = "pattern_repeat2",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_expression_repeat2] = "expression_repeat2",
  [aux_sym_extractor_repeat1] = "extractor_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_decl] = anon_sym_decl,
  [anon_sym_rule] = anon_sym_rule,
  [anon_sym_extractor] = anon_sym_extractor,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_constructor] = anon_sym_constructor,
  [anon_sym_infallible] = anon_sym_infallible,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_primitive] = anon_sym_primitive,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_pure] = anon_sym_pure,
  [anon_sym_partial] = anon_sym_partial,
  [anon_sym__] = anon_sym__,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_if_DASHlet] = anon_sym_if_DASHlet,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_let] = anon_sym_let,
  [sym_constant] = sym_constant,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [aux_sym_integer_token2] = aux_sym_integer_token2,
  [aux_sym_integer_token3] = aux_sym_integer_token3,
  [aux_sym_integer_token4] = aux_sym_integer_token4,
  [anon_sym_POUNDt] = anon_sym_POUNDt,
  [anon_sym_POUNDf] = anon_sym_POUNDf,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_defn] = sym_defn,
  [sym_type_decl] = sym_type_decl,
  [sym_type_value] = sym_type_value,
  [sym_extern] = sym_extern,
  [sym_primitive] = sym_primitive,
  [sym_enum] = sym_enum,
  [sym_enum_variant] = sym_enum_variant,
  [sym_enum_field] = sym_enum_field,
  [sym_type] = sym_type,
  [sym_decl] = sym_decl,
  [sym_rule] = sym_rule,
  [sym_priority] = sym_priority,
  [sym_pattern] = sym_pattern,
  [sym_pattern_arg] = sym_pattern_arg,
  [sym_condition] = sym_condition,
  [sym_if_let] = sym_if_let,
  [sym_if] = sym_if,
  [sym_expression] = sym_expression,
  [sym_let_binding] = sym_let_binding,
  [sym_extractor] = sym_extractor,
  [sym_integer] = sym_integer,
  [sym_boolean] = sym_boolean,
  [sym_line_comment] = sym_line_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_enum_repeat1] = aux_sym_enum_repeat1,
  [aux_sym_enum_variant_repeat1] = aux_sym_enum_variant_repeat1,
  [aux_sym_decl_repeat1] = aux_sym_decl_repeat1,
  [aux_sym_decl_repeat2] = aux_sym_decl_repeat2,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_pattern_repeat2] = aux_sym_pattern_repeat2,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_expression_repeat2] = aux_sym_expression_repeat2,
  [aux_sym_extractor_repeat1] = aux_sym_extractor_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extractor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_constructor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_infallible] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_primitive] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_partial] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if_DASHlet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUNDt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_type_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_value] = {
    .visible = true,
    .named = true,
  },
  [sym_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_if_let] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_let_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_extractor] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_variant_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extractor_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '0') ADVANCE(23);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '<') ADVANCE(16);
      if (lookahead == '@') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '0') ADVANCE(23);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '<') ADVANCE(16);
      if (lookahead == '@') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '0') ADVANCE(23);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(27);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_if_DASHlet);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_constant);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == 'b') ADVANCE(9);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_integer_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_integer_token3);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_integer_token4);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_POUNDt);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUNDf);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '_') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'd') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == 'l') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == 't') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead == 'x') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_decl);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_pure);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_rule);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_const);
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 48:
      if (lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 50:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(60);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(63);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 60:
      if (lookahead == 'b') ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_partial);
      END_STATE();
    case 62:
      if (lookahead == 'v') ADVANCE(66);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_extractor);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_primitive);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_infallible);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_constructor);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 32},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 1},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 1},
  [142] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_decl] = ACTIONS(1),
    [anon_sym_rule] = ACTIONS(1),
    [anon_sym_extractor] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_constructor] = ACTIONS(1),
    [anon_sym_infallible] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_primitive] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_pure] = ACTIONS(1),
    [anon_sym_partial] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_if_DASHlet] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [sym_constant] = ACTIONS(1),
    [aux_sym_integer_token1] = ACTIONS(1),
    [aux_sym_integer_token2] = ACTIONS(1),
    [aux_sym_integer_token3] = ACTIONS(1),
    [aux_sym_integer_token4] = ACTIONS(1),
    [anon_sym_POUNDt] = ACTIONS(1),
    [anon_sym_POUNDf] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(140),
    [sym_defn] = STATE(84),
    [sym_line_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(55),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    STATE(2), 1,
      sym_line_comment,
    STATE(4), 1,
      aux_sym_rule_repeat1,
    STATE(45), 1,
      sym_condition,
    STATE(135), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    STATE(46), 2,
      sym_if_let,
      sym_if,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [43] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    STATE(3), 1,
      sym_line_comment,
    STATE(5), 1,
      aux_sym_rule_repeat1,
    STATE(45), 1,
      sym_condition,
    STATE(110), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    STATE(46), 2,
      sym_if_let,
      sym_if,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [86] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    STATE(4), 1,
      sym_line_comment,
    STATE(13), 1,
      aux_sym_rule_repeat1,
    STATE(45), 1,
      sym_condition,
    STATE(110), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    STATE(46), 2,
      sym_if_let,
      sym_if,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [129] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    STATE(5), 1,
      sym_line_comment,
    STATE(13), 1,
      aux_sym_rule_repeat1,
    STATE(45), 1,
      sym_condition,
    STATE(124), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    STATE(46), 2,
      sym_if_let,
      sym_if,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [172] = 10,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(22), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
    ACTIONS(27), 1,
      aux_sym_integer_token1,
    STATE(42), 1,
      sym_expression,
    ACTIONS(19), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(33), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(6), 2,
      sym_line_comment,
      aux_sym_expression_repeat2,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(30), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [209] = 14,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(46), 1,
      sym_constant,
    STATE(7), 1,
      sym_line_comment,
    STATE(9), 1,
      aux_sym_pattern_repeat2,
    STATE(20), 1,
      sym_integer,
    STATE(35), 1,
      sym_pattern,
    STATE(40), 1,
      sym_pattern_arg,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [254] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_line_comment,
    STATE(11), 1,
      aux_sym_expression_repeat2,
    STATE(42), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [293] = 14,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(46), 1,
      sym_constant,
    ACTIONS(52), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_line_comment,
    STATE(10), 1,
      aux_sym_pattern_repeat2,
    STATE(20), 1,
      sym_integer,
    STATE(35), 1,
      sym_pattern,
    STATE(40), 1,
      sym_pattern_arg,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [338] = 13,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(54), 1,
      sym_identifier,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    ACTIONS(62), 1,
      anon_sym__,
    ACTIONS(65), 1,
      anon_sym_LT,
    ACTIONS(68), 1,
      sym_constant,
    ACTIONS(71), 1,
      aux_sym_integer_token1,
    STATE(20), 1,
      sym_integer,
    STATE(35), 1,
      sym_pattern,
    STATE(40), 1,
      sym_pattern_arg,
    STATE(10), 2,
      sym_line_comment,
      aux_sym_pattern_repeat2,
    ACTIONS(74), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [381] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      aux_sym_expression_repeat2,
    STATE(11), 1,
      sym_line_comment,
    STATE(42), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [420] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(83), 1,
      anon_sym_AT,
    STATE(12), 1,
      sym_line_comment,
    ACTIONS(79), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(81), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [446] = 7,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      aux_sym_integer_token1,
    STATE(45), 1,
      sym_condition,
    STATE(13), 2,
      sym_line_comment,
      aux_sym_rule_repeat1,
    STATE(46), 2,
      sym_if_let,
      sym_if,
    ACTIONS(85), 7,
      sym_identifier,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [476] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(14), 1,
      sym_line_comment,
    ACTIONS(92), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(94), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [499] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(15), 1,
      sym_line_comment,
    ACTIONS(96), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(98), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [522] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      sym_line_comment,
    ACTIONS(100), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(102), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [545] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      sym_line_comment,
    ACTIONS(104), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(106), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [568] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_line_comment,
    STATE(112), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [601] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    STATE(2), 1,
      sym_pattern,
    STATE(19), 1,
      sym_line_comment,
    STATE(39), 1,
      sym_integer,
    STATE(41), 1,
      sym_priority,
    STATE(106), 1,
      sym_rule,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [640] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(20), 1,
      sym_line_comment,
    ACTIONS(79), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(81), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [663] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(21), 1,
      sym_line_comment,
    ACTIONS(108), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(110), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [686] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_line_comment,
    STATE(129), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [719] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(23), 1,
      sym_line_comment,
    ACTIONS(112), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(114), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [742] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(116), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(118), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [765] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_line_comment,
    STATE(139), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [798] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    STATE(20), 1,
      sym_integer,
    STATE(26), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym_pattern_repeat1,
    STATE(47), 1,
      sym_pattern,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [837] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(120), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_LPAREN,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    ACTIONS(128), 1,
      anon_sym__,
    ACTIONS(131), 1,
      sym_constant,
    ACTIONS(134), 1,
      aux_sym_integer_token1,
    STATE(20), 1,
      sym_integer,
    STATE(47), 1,
      sym_pattern,
    STATE(27), 2,
      sym_line_comment,
      aux_sym_pattern_repeat1,
    ACTIONS(137), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [874] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(140), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(142), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [897] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(29), 1,
      sym_line_comment,
    ACTIONS(144), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(146), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [920] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_line_comment,
    STATE(137), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [953] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_line_comment,
    STATE(103), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [986] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    ACTIONS(52), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_integer,
    STATE(27), 1,
      aux_sym_pattern_repeat1,
    STATE(32), 1,
      sym_line_comment,
    STATE(47), 1,
      sym_pattern,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1025] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_line_comment,
    STATE(37), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_identifier,
      sym_constant,
    ACTIONS(17), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(16), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1058] = 10,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    STATE(20), 1,
      sym_integer,
    STATE(34), 1,
      sym_line_comment,
    STATE(120), 1,
      sym_pattern,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1091] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(35), 1,
      sym_line_comment,
    ACTIONS(148), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(150), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1112] = 10,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    STATE(20), 1,
      sym_integer,
    STATE(36), 1,
      sym_line_comment,
    STATE(105), 1,
      sym_pattern,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1145] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      sym_line_comment,
    ACTIONS(152), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(154), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1166] = 10,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    STATE(20), 1,
      sym_integer,
    STATE(24), 1,
      sym_pattern,
    STATE(38), 1,
      sym_line_comment,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1199] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(162), 1,
      anon_sym__,
    STATE(39), 1,
      sym_line_comment,
    ACTIONS(81), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(156), 2,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(159), 5,
      anon_sym_LPAREN,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1224] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(40), 1,
      sym_line_comment,
    ACTIONS(164), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(166), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1245] = 10,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    STATE(3), 1,
      sym_pattern,
    STATE(20), 1,
      sym_integer,
    STATE(41), 1,
      sym_line_comment,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1278] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(170), 1,
      aux_sym_integer_token1,
    STATE(42), 1,
      sym_line_comment,
    ACTIONS(168), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1299] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(174), 1,
      aux_sym_integer_token1,
    STATE(43), 1,
      sym_line_comment,
    ACTIONS(172), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1320] = 10,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_integer_token1,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym__,
    ACTIONS(46), 1,
      sym_constant,
    STATE(18), 1,
      sym_pattern,
    STATE(20), 1,
      sym_integer,
    STATE(44), 1,
      sym_line_comment,
    ACTIONS(15), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1353] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(178), 1,
      aux_sym_integer_token1,
    STATE(45), 1,
      sym_line_comment,
    ACTIONS(176), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1373] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(182), 1,
      aux_sym_integer_token1,
    STATE(46), 1,
      sym_line_comment,
    ACTIONS(180), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1393] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      sym_line_comment,
    ACTIONS(184), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(186), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1413] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(190), 1,
      aux_sym_integer_token1,
    STATE(48), 1,
      sym_line_comment,
    ACTIONS(188), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1433] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(194), 1,
      aux_sym_integer_token1,
    STATE(49), 1,
      sym_line_comment,
    ACTIONS(192), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_constant,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1453] = 7,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(196), 1,
      anon_sym_type,
    ACTIONS(198), 1,
      anon_sym_decl,
    ACTIONS(200), 1,
      anon_sym_rule,
    ACTIONS(202), 1,
      anon_sym_extractor,
    ACTIONS(204), 1,
      anon_sym_extern,
    STATE(50), 1,
      sym_line_comment,
  [1475] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(206), 1,
      sym_identifier,
    STATE(51), 1,
      sym_line_comment,
    STATE(70), 1,
      aux_sym_decl_repeat1,
    STATE(106), 1,
      sym_decl,
    ACTIONS(208), 2,
      anon_sym_pure,
      anon_sym_partial,
  [1495] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 2,
      anon_sym_pure,
      anon_sym_partial,
    STATE(52), 2,
      sym_line_comment,
      aux_sym_decl_repeat1,
  [1510] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(215), 1,
      anon_sym_LPAREN,
    ACTIONS(217), 1,
      anon_sym_enum,
    STATE(53), 1,
      sym_line_comment,
    STATE(117), 2,
      sym_primitive,
      sym_enum,
  [1527] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_line_comment,
    STATE(68), 1,
      aux_sym_decl_repeat2,
    STATE(100), 1,
      sym_type,
  [1546] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    STATE(55), 1,
      sym_line_comment,
    STATE(64), 1,
      aux_sym_source_file_repeat1,
    STATE(84), 1,
      sym_defn,
  [1565] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(225), 1,
      sym_identifier,
    ACTIONS(227), 1,
      anon_sym_if_DASHlet,
    ACTIONS(229), 1,
      anon_sym_if,
    ACTIONS(231), 1,
      anon_sym_let,
    STATE(56), 1,
      sym_line_comment,
  [1584] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(233), 1,
      anon_sym_LPAREN,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      sym_enum_field,
    STATE(57), 2,
      sym_line_comment,
      aux_sym_enum_variant_repeat1,
  [1601] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(238), 1,
      sym_identifier,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(100), 1,
      sym_type,
    STATE(58), 2,
      sym_line_comment,
      aux_sym_decl_repeat2,
  [1618] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(243), 1,
      anon_sym_LPAREN,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_let_binding,
    STATE(59), 2,
      sym_line_comment,
      aux_sym_expression_repeat1,
  [1635] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_enum_variant_repeat1,
    STATE(60), 1,
      sym_line_comment,
    STATE(91), 1,
      sym_enum_field,
  [1654] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(252), 1,
      anon_sym_extractor,
    ACTIONS(254), 1,
      anon_sym_constructor,
    ACTIONS(256), 1,
      anon_sym_const,
    STATE(61), 1,
      sym_line_comment,
    STATE(106), 1,
      sym_extern,
  [1673] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_expression_repeat1,
    STATE(62), 1,
      sym_line_comment,
    STATE(98), 1,
      sym_let_binding,
  [1692] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(262), 1,
      anon_sym_LPAREN,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym_line_comment,
    STATE(65), 1,
      aux_sym_enum_repeat1,
    STATE(86), 1,
      sym_enum_variant,
  [1711] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(266), 1,
      ts_builtin_sym_end,
    ACTIONS(268), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_defn,
    STATE(64), 2,
      sym_line_comment,
      aux_sym_source_file_repeat1,
  [1728] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(262), 1,
      anon_sym_LPAREN,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_line_comment,
    STATE(66), 1,
      aux_sym_enum_repeat1,
    STATE(86), 1,
      sym_enum_variant,
  [1747] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(273), 1,
      anon_sym_LPAREN,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym_enum_variant,
    STATE(66), 2,
      sym_line_comment,
      aux_sym_enum_repeat1,
  [1764] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_enum_variant_repeat1,
    STATE(67), 1,
      sym_line_comment,
    STATE(91), 1,
      sym_enum_field,
  [1783] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_decl_repeat2,
    STATE(68), 1,
      sym_line_comment,
    STATE(100), 1,
      sym_type,
  [1802] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_line_comment,
    STATE(72), 1,
      aux_sym_decl_repeat2,
    STATE(100), 1,
      sym_type,
  [1821] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(282), 1,
      sym_identifier,
    STATE(52), 1,
      aux_sym_decl_repeat1,
    STATE(70), 1,
      sym_line_comment,
    ACTIONS(208), 2,
      anon_sym_pure,
      anon_sym_partial,
  [1838] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_expression_repeat1,
    STATE(71), 1,
      sym_line_comment,
    STATE(98), 1,
      sym_let_binding,
  [1857] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_decl_repeat2,
    STATE(72), 1,
      sym_line_comment,
    STATE(100), 1,
      sym_type,
  [1876] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(288), 1,
      anon_sym_LPAREN,
    ACTIONS(290), 1,
      anon_sym_extern,
    STATE(73), 1,
      sym_line_comment,
    STATE(116), 1,
      sym_type_value,
  [1892] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(292), 1,
      sym_identifier,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
    STATE(74), 2,
      sym_line_comment,
      aux_sym_extractor_repeat1,
  [1906] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(75), 1,
      sym_line_comment,
    ACTIONS(297), 3,
      anon_sym_pure,
      anon_sym_partial,
      sym_identifier,
  [1918] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(299), 1,
      sym_identifier,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym_extractor_repeat1,
  [1934] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(299), 1,
      sym_identifier,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_extractor_repeat1,
    STATE(77), 1,
      sym_line_comment,
  [1950] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(305), 1,
      sym_identifier,
    ACTIONS(307), 1,
      anon_sym_and,
    STATE(78), 1,
      sym_line_comment,
  [1963] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(227), 1,
      anon_sym_if_DASHlet,
    ACTIONS(229), 1,
      anon_sym_if,
    STATE(79), 1,
      sym_line_comment,
  [1976] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(80), 1,
      sym_line_comment,
    ACTIONS(309), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1987] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(81), 1,
      sym_line_comment,
    ACTIONS(311), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1998] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(82), 1,
      sym_line_comment,
    ACTIONS(313), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2009] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(83), 1,
      sym_line_comment,
    STATE(108), 1,
      sym_type,
  [2022] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      sym_line_comment,
    ACTIONS(315), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [2033] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(85), 1,
      sym_line_comment,
    ACTIONS(317), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2044] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(86), 1,
      sym_line_comment,
    ACTIONS(319), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2055] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(87), 1,
      sym_line_comment,
    STATE(138), 1,
      sym_type,
  [2068] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(25), 1,
      sym_type,
    STATE(88), 1,
      sym_line_comment,
  [2081] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(89), 1,
      sym_line_comment,
    STATE(111), 1,
      sym_type,
  [2094] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(321), 1,
      sym_identifier,
    STATE(90), 1,
      sym_line_comment,
    STATE(106), 1,
      sym_type_decl,
  [2107] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(91), 1,
      sym_line_comment,
    ACTIONS(323), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2118] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(225), 1,
      sym_identifier,
    ACTIONS(231), 1,
      anon_sym_let,
    STATE(92), 1,
      sym_line_comment,
  [2131] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(325), 1,
      sym_identifier,
    ACTIONS(327), 1,
      anon_sym_infallible,
    STATE(93), 1,
      sym_line_comment,
  [2144] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(288), 1,
      anon_sym_LPAREN,
    STATE(94), 1,
      sym_line_comment,
    STATE(115), 1,
      sym_type_value,
  [2157] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(95), 1,
      sym_line_comment,
    ACTIONS(329), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2168] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(96), 1,
      sym_line_comment,
    ACTIONS(331), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [2179] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(333), 1,
      anon_sym_LPAREN,
    STATE(97), 1,
      sym_line_comment,
    STATE(106), 1,
      sym_extractor,
  [2192] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(98), 1,
      sym_line_comment,
    ACTIONS(335), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2203] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(99), 1,
      sym_line_comment,
    STATE(132), 1,
      sym_type,
  [2216] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(100), 1,
      sym_line_comment,
    ACTIONS(337), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2227] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      sym_identifier,
    STATE(101), 1,
      sym_line_comment,
    STATE(126), 1,
      sym_type,
  [2240] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(339), 1,
      sym_identifier,
    STATE(102), 1,
      sym_line_comment,
  [2250] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(341), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      sym_line_comment,
  [2260] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(343), 1,
      anon_sym_LPAREN,
    STATE(104), 1,
      sym_line_comment,
  [2270] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(345), 1,
      anon_sym_RPAREN,
    STATE(105), 1,
      sym_line_comment,
  [2280] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      sym_line_comment,
  [2290] = 3,
    ACTIONS(349), 1,
      anon_sym_SEMI,
    ACTIONS(351), 1,
      aux_sym_line_comment_token1,
    STATE(107), 1,
      sym_line_comment,
  [2300] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(353), 1,
      anon_sym_RPAREN,
    STATE(108), 1,
      sym_line_comment,
  [2310] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(355), 1,
      anon_sym_RPAREN,
    STATE(109), 1,
      sym_line_comment,
  [2320] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(357), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      sym_line_comment,
  [2330] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(359), 1,
      anon_sym_RPAREN,
    STATE(111), 1,
      sym_line_comment,
  [2340] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(361), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      sym_line_comment,
  [2350] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(363), 1,
      sym_identifier,
    STATE(113), 1,
      sym_line_comment,
  [2360] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(365), 1,
      sym_identifier,
    STATE(114), 1,
      sym_line_comment,
  [2370] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(367), 1,
      anon_sym_RPAREN,
    STATE(115), 1,
      sym_line_comment,
  [2380] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(369), 1,
      anon_sym_RPAREN,
    STATE(116), 1,
      sym_line_comment,
  [2390] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(371), 1,
      anon_sym_RPAREN,
    STATE(117), 1,
      sym_line_comment,
  [2400] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(373), 1,
      anon_sym_primitive,
    STATE(118), 1,
      sym_line_comment,
  [2410] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(375), 1,
      anon_sym_LPAREN,
    STATE(119), 1,
      sym_line_comment,
  [2420] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(377), 1,
      anon_sym_RPAREN,
    STATE(120), 1,
      sym_line_comment,
  [2430] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(379), 1,
      anon_sym_RPAREN,
    STATE(121), 1,
      sym_line_comment,
  [2440] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(381), 1,
      sym_identifier,
    STATE(122), 1,
      sym_line_comment,
  [2450] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(383), 1,
      anon_sym_LPAREN,
    STATE(123), 1,
      sym_line_comment,
  [2460] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
    STATE(124), 1,
      sym_line_comment,
  [2470] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(387), 1,
      sym_identifier,
    STATE(125), 1,
      sym_line_comment,
  [2480] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(389), 1,
      anon_sym_RPAREN,
    STATE(126), 1,
      sym_line_comment,
  [2490] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(391), 1,
      sym_identifier,
    STATE(127), 1,
      sym_line_comment,
  [2500] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(393), 1,
      sym_constant,
    STATE(128), 1,
      sym_line_comment,
  [2510] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(395), 1,
      anon_sym_RPAREN,
    STATE(129), 1,
      sym_line_comment,
  [2520] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(397), 1,
      anon_sym_RPAREN,
    STATE(130), 1,
      sym_line_comment,
  [2530] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(399), 1,
      sym_identifier,
    STATE(131), 1,
      sym_line_comment,
  [2540] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(401), 1,
      anon_sym_RPAREN,
    STATE(132), 1,
      sym_line_comment,
  [2550] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(403), 1,
      anon_sym_RPAREN,
    STATE(133), 1,
      sym_line_comment,
  [2560] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(405), 1,
      sym_identifier,
    STATE(134), 1,
      sym_line_comment,
  [2570] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(407), 1,
      anon_sym_RPAREN,
    STATE(135), 1,
      sym_line_comment,
  [2580] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(409), 1,
      sym_identifier,
    STATE(136), 1,
      sym_line_comment,
  [2590] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(411), 1,
      anon_sym_RPAREN,
    STATE(137), 1,
      sym_line_comment,
  [2600] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(413), 1,
      anon_sym_RPAREN,
    STATE(138), 1,
      sym_line_comment,
  [2610] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(415), 1,
      anon_sym_RPAREN,
    STATE(139), 1,
      sym_line_comment,
  [2620] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(417), 1,
      ts_builtin_sym_end,
    STATE(140), 1,
      sym_line_comment,
  [2630] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(419), 1,
      sym_identifier,
    STATE(141), 1,
      sym_line_comment,
  [2640] = 1,
    ACTIONS(421), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 172,
  [SMALL_STATE(7)] = 209,
  [SMALL_STATE(8)] = 254,
  [SMALL_STATE(9)] = 293,
  [SMALL_STATE(10)] = 338,
  [SMALL_STATE(11)] = 381,
  [SMALL_STATE(12)] = 420,
  [SMALL_STATE(13)] = 446,
  [SMALL_STATE(14)] = 476,
  [SMALL_STATE(15)] = 499,
  [SMALL_STATE(16)] = 522,
  [SMALL_STATE(17)] = 545,
  [SMALL_STATE(18)] = 568,
  [SMALL_STATE(19)] = 601,
  [SMALL_STATE(20)] = 640,
  [SMALL_STATE(21)] = 663,
  [SMALL_STATE(22)] = 686,
  [SMALL_STATE(23)] = 719,
  [SMALL_STATE(24)] = 742,
  [SMALL_STATE(25)] = 765,
  [SMALL_STATE(26)] = 798,
  [SMALL_STATE(27)] = 837,
  [SMALL_STATE(28)] = 874,
  [SMALL_STATE(29)] = 897,
  [SMALL_STATE(30)] = 920,
  [SMALL_STATE(31)] = 953,
  [SMALL_STATE(32)] = 986,
  [SMALL_STATE(33)] = 1025,
  [SMALL_STATE(34)] = 1058,
  [SMALL_STATE(35)] = 1091,
  [SMALL_STATE(36)] = 1112,
  [SMALL_STATE(37)] = 1145,
  [SMALL_STATE(38)] = 1166,
  [SMALL_STATE(39)] = 1199,
  [SMALL_STATE(40)] = 1224,
  [SMALL_STATE(41)] = 1245,
  [SMALL_STATE(42)] = 1278,
  [SMALL_STATE(43)] = 1299,
  [SMALL_STATE(44)] = 1320,
  [SMALL_STATE(45)] = 1353,
  [SMALL_STATE(46)] = 1373,
  [SMALL_STATE(47)] = 1393,
  [SMALL_STATE(48)] = 1413,
  [SMALL_STATE(49)] = 1433,
  [SMALL_STATE(50)] = 1453,
  [SMALL_STATE(51)] = 1475,
  [SMALL_STATE(52)] = 1495,
  [SMALL_STATE(53)] = 1510,
  [SMALL_STATE(54)] = 1527,
  [SMALL_STATE(55)] = 1546,
  [SMALL_STATE(56)] = 1565,
  [SMALL_STATE(57)] = 1584,
  [SMALL_STATE(58)] = 1601,
  [SMALL_STATE(59)] = 1618,
  [SMALL_STATE(60)] = 1635,
  [SMALL_STATE(61)] = 1654,
  [SMALL_STATE(62)] = 1673,
  [SMALL_STATE(63)] = 1692,
  [SMALL_STATE(64)] = 1711,
  [SMALL_STATE(65)] = 1728,
  [SMALL_STATE(66)] = 1747,
  [SMALL_STATE(67)] = 1764,
  [SMALL_STATE(68)] = 1783,
  [SMALL_STATE(69)] = 1802,
  [SMALL_STATE(70)] = 1821,
  [SMALL_STATE(71)] = 1838,
  [SMALL_STATE(72)] = 1857,
  [SMALL_STATE(73)] = 1876,
  [SMALL_STATE(74)] = 1892,
  [SMALL_STATE(75)] = 1906,
  [SMALL_STATE(76)] = 1918,
  [SMALL_STATE(77)] = 1934,
  [SMALL_STATE(78)] = 1950,
  [SMALL_STATE(79)] = 1963,
  [SMALL_STATE(80)] = 1976,
  [SMALL_STATE(81)] = 1987,
  [SMALL_STATE(82)] = 1998,
  [SMALL_STATE(83)] = 2009,
  [SMALL_STATE(84)] = 2022,
  [SMALL_STATE(85)] = 2033,
  [SMALL_STATE(86)] = 2044,
  [SMALL_STATE(87)] = 2055,
  [SMALL_STATE(88)] = 2068,
  [SMALL_STATE(89)] = 2081,
  [SMALL_STATE(90)] = 2094,
  [SMALL_STATE(91)] = 2107,
  [SMALL_STATE(92)] = 2118,
  [SMALL_STATE(93)] = 2131,
  [SMALL_STATE(94)] = 2144,
  [SMALL_STATE(95)] = 2157,
  [SMALL_STATE(96)] = 2168,
  [SMALL_STATE(97)] = 2179,
  [SMALL_STATE(98)] = 2192,
  [SMALL_STATE(99)] = 2203,
  [SMALL_STATE(100)] = 2216,
  [SMALL_STATE(101)] = 2227,
  [SMALL_STATE(102)] = 2240,
  [SMALL_STATE(103)] = 2250,
  [SMALL_STATE(104)] = 2260,
  [SMALL_STATE(105)] = 2270,
  [SMALL_STATE(106)] = 2280,
  [SMALL_STATE(107)] = 2290,
  [SMALL_STATE(108)] = 2300,
  [SMALL_STATE(109)] = 2310,
  [SMALL_STATE(110)] = 2320,
  [SMALL_STATE(111)] = 2330,
  [SMALL_STATE(112)] = 2340,
  [SMALL_STATE(113)] = 2350,
  [SMALL_STATE(114)] = 2360,
  [SMALL_STATE(115)] = 2370,
  [SMALL_STATE(116)] = 2380,
  [SMALL_STATE(117)] = 2390,
  [SMALL_STATE(118)] = 2400,
  [SMALL_STATE(119)] = 2410,
  [SMALL_STATE(120)] = 2420,
  [SMALL_STATE(121)] = 2430,
  [SMALL_STATE(122)] = 2440,
  [SMALL_STATE(123)] = 2450,
  [SMALL_STATE(124)] = 2460,
  [SMALL_STATE(125)] = 2470,
  [SMALL_STATE(126)] = 2480,
  [SMALL_STATE(127)] = 2490,
  [SMALL_STATE(128)] = 2500,
  [SMALL_STATE(129)] = 2510,
  [SMALL_STATE(130)] = 2520,
  [SMALL_STATE(131)] = 2530,
  [SMALL_STATE(132)] = 2540,
  [SMALL_STATE(133)] = 2550,
  [SMALL_STATE(134)] = 2560,
  [SMALL_STATE(135)] = 2570,
  [SMALL_STATE(136)] = 2580,
  [SMALL_STATE(137)] = 2590,
  [SMALL_STATE(138)] = 2600,
  [SMALL_STATE(139)] = 2610,
  [SMALL_STATE(140)] = 2620,
  [SMALL_STATE(141)] = 2630,
  [SMALL_STATE(142)] = 2640,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(16),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(92),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(14),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(14),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(29),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(78),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(20),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(33),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(20),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(14),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2), SHIFT_REPEAT(79),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 7),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 7),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 6),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 6),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(12),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(78),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(20),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(20),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(14),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(14),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 4),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 4),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern_arg, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_arg, 1),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern_arg, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_arg, 2),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_priority, 1), REDUCE(sym_pattern, 1),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_priority, 1), REDUCE(sym_pattern, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_priority, 1),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 1),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat2, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 1),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 4),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 4),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_let, 5),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_let, 5),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_decl_repeat1, 2),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_decl_repeat1, 2), SHIFT_REPEAT(75),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_variant_repeat1, 2), SHIFT_REPEAT(122),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_variant_repeat1, 2),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decl_repeat2, 2), SHIFT_REPEAT(43),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decl_repeat2, 2),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(114),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 2),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2), SHIFT_REPEAT(136),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [292] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extractor_repeat1, 2), SHIFT_REPEAT(80),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extractor_repeat1, 2),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_decl_repeat1, 1),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extractor_repeat1, 1),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 5),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_field, 4),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 1),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_variant_repeat1, 1),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 3),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 4),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 1),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decl_repeat2, 1),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extractor, 4),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [349] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 4),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 5),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 3),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 2),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extractor, 5),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 4),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 6),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [397] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 3),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 4),
  [403] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 3),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [407] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [417] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [421] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_isle(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
