#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 143
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_type = 3,
  anon_sym_decl = 4,
  anon_sym_rule = 5,
  anon_sym_extractor = 6,
  anon_sym_extern = 7,
  anon_sym_RPAREN = 8,
  anon_sym_constructor = 9,
  anon_sym_infallible = 10,
  anon_sym_const = 11,
  anon_sym_primitive = 12,
  anon_sym_enum = 13,
  anon_sym_pure = 14,
  anon_sym_partial = 15,
  anon_sym__ = 16,
  anon_sym_AT = 17,
  anon_sym_and = 18,
  anon_sym_LT = 19,
  anon_sym_if_DASHlet = 20,
  anon_sym_if = 21,
  anon_sym_let = 22,
  sym_const_sym = 23,
  aux_sym_integer_token1 = 24,
  aux_sym_integer_token2 = 25,
  aux_sym_integer_token3 = 26,
  aux_sym_integer_token4 = 27,
  anon_sym_POUNDt = 28,
  anon_sym_POUNDf = 29,
  anon_sym_SEMI = 30,
  aux_sym_line_comment_token1 = 31,
  sym_source_file = 32,
  sym_defn = 33,
  sym_type_decl = 34,
  sym_type_value = 35,
  sym_extern = 36,
  sym_primitive = 37,
  sym_enum = 38,
  sym_enum_variant = 39,
  sym_enum_field = 40,
  sym_type = 41,
  sym_decl = 42,
  sym_rule = 43,
  sym_priority = 44,
  sym_pattern = 45,
  sym_pattern_arg = 46,
  sym_condition = 47,
  sym_if_let = 48,
  sym_if = 49,
  sym_expression = 50,
  sym_let_binding = 51,
  sym_extractor = 52,
  sym_integer = 53,
  sym_boolean = 54,
  sym_line_comment = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_enum_repeat1 = 57,
  aux_sym_enum_variant_repeat1 = 58,
  aux_sym_decl_repeat1 = 59,
  aux_sym_decl_repeat2 = 60,
  aux_sym_rule_repeat1 = 61,
  aux_sym_pattern_repeat1 = 62,
  aux_sym_pattern_repeat2 = 63,
  aux_sym_expression_repeat1 = 64,
  aux_sym_expression_repeat2 = 65,
  aux_sym_extractor_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_type] = "type",
  [anon_sym_decl] = "decl",
  [anon_sym_rule] = "rule",
  [anon_sym_extractor] = "extractor",
  [anon_sym_extern] = "extern",
  [anon_sym_RPAREN] = ")",
  [anon_sym_constructor] = "constructor",
  [anon_sym_infallible] = "infallible",
  [anon_sym_const] = "const",
  [anon_sym_primitive] = "primitive",
  [anon_sym_enum] = "enum",
  [anon_sym_pure] = "pure",
  [anon_sym_partial] = "partial",
  [anon_sym__] = "_",
  [anon_sym_AT] = "@",
  [anon_sym_and] = "and",
  [anon_sym_LT] = "<",
  [anon_sym_if_DASHlet] = "if-let",
  [anon_sym_if] = "if",
  [anon_sym_let] = "let",
  [sym_const_sym] = "const_sym",
  [aux_sym_integer_token1] = "integer_token1",
  [aux_sym_integer_token2] = "integer_token2",
  [aux_sym_integer_token3] = "integer_token3",
  [aux_sym_integer_token4] = "integer_token4",
  [anon_sym_POUNDt] = "#t",
  [anon_sym_POUNDf] = "#f",
  [anon_sym_SEMI] = ";",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [sym_source_file] = "source_file",
  [sym_defn] = "defn",
  [sym_type_decl] = "type_decl",
  [sym_type_value] = "type_value",
  [sym_extern] = "extern",
  [sym_primitive] = "primitive",
  [sym_enum] = "enum",
  [sym_enum_variant] = "enum_variant",
  [sym_enum_field] = "enum_field",
  [sym_type] = "type",
  [sym_decl] = "decl",
  [sym_rule] = "rule",
  [sym_priority] = "priority",
  [sym_pattern] = "pattern",
  [sym_pattern_arg] = "pattern_arg",
  [sym_condition] = "condition",
  [sym_if_let] = "if_let",
  [sym_if] = "if",
  [sym_expression] = "expression",
  [sym_let_binding] = "let_binding",
  [sym_extractor] = "extractor",
  [sym_integer] = "integer",
  [sym_boolean] = "boolean",
  [sym_line_comment] = "line_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_enum_repeat1] = "enum_repeat1",
  [aux_sym_enum_variant_repeat1] = "enum_variant_repeat1",
  [aux_sym_decl_repeat1] = "decl_repeat1",
  [aux_sym_decl_repeat2] = "decl_repeat2",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_pattern_repeat2] = "pattern_repeat2",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_expression_repeat2] = "expression_repeat2",
  [aux_sym_extractor_repeat1] = "extractor_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_decl] = anon_sym_decl,
  [anon_sym_rule] = anon_sym_rule,
  [anon_sym_extractor] = anon_sym_extractor,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_constructor] = anon_sym_constructor,
  [anon_sym_infallible] = anon_sym_infallible,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_primitive] = anon_sym_primitive,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_pure] = anon_sym_pure,
  [anon_sym_partial] = anon_sym_partial,
  [anon_sym__] = anon_sym__,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_if_DASHlet] = anon_sym_if_DASHlet,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_let] = anon_sym_let,
  [sym_const_sym] = sym_const_sym,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [aux_sym_integer_token2] = aux_sym_integer_token2,
  [aux_sym_integer_token3] = aux_sym_integer_token3,
  [aux_sym_integer_token4] = aux_sym_integer_token4,
  [anon_sym_POUNDt] = anon_sym_POUNDt,
  [anon_sym_POUNDf] = anon_sym_POUNDf,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_defn] = sym_defn,
  [sym_type_decl] = sym_type_decl,
  [sym_type_value] = sym_type_value,
  [sym_extern] = sym_extern,
  [sym_primitive] = sym_primitive,
  [sym_enum] = sym_enum,
  [sym_enum_variant] = sym_enum_variant,
  [sym_enum_field] = sym_enum_field,
  [sym_type] = sym_type,
  [sym_decl] = sym_decl,
  [sym_rule] = sym_rule,
  [sym_priority] = sym_priority,
  [sym_pattern] = sym_pattern,
  [sym_pattern_arg] = sym_pattern_arg,
  [sym_condition] = sym_condition,
  [sym_if_let] = sym_if_let,
  [sym_if] = sym_if,
  [sym_expression] = sym_expression,
  [sym_let_binding] = sym_let_binding,
  [sym_extractor] = sym_extractor,
  [sym_integer] = sym_integer,
  [sym_boolean] = sym_boolean,
  [sym_line_comment] = sym_line_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_enum_repeat1] = aux_sym_enum_repeat1,
  [aux_sym_enum_variant_repeat1] = aux_sym_enum_variant_repeat1,
  [aux_sym_decl_repeat1] = aux_sym_decl_repeat1,
  [aux_sym_decl_repeat2] = aux_sym_decl_repeat2,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_pattern_repeat2] = aux_sym_pattern_repeat2,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_expression_repeat2] = aux_sym_expression_repeat2,
  [aux_sym_extractor_repeat1] = aux_sym_extractor_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extractor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_constructor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_infallible] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_primitive] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_partial] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if_DASHlet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [sym_const_sym] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUNDt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_type_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_value] = {
    .visible = true,
    .named = true,
  },
  [sym_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_if_let] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_let_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_extractor] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_variant_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extractor_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '0') ADVANCE(23);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '<') ADVANCE(16);
      if (lookahead == '@') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '0') ADVANCE(23);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '<') ADVANCE(16);
      if (lookahead == '@') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '0') ADVANCE(23);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(27);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_if_DASHlet);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_const_sym);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == 'b') ADVANCE(9);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_integer_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_integer_token3);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_integer_token4);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_POUNDt);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUNDf);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '_') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'd') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == 'l') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == 't') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead == 'x') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_decl);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_pure);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_rule);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_const);
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 48:
      if (lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 50:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(60);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(63);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 60:
      if (lookahead == 'b') ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_partial);
      END_STATE();
    case 62:
      if (lookahead == 'v') ADVANCE(66);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_extractor);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_primitive);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_infallible);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_constructor);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 32},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 1},
  [135] = {.lex_state = 1},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_decl] = ACTIONS(1),
    [anon_sym_rule] = ACTIONS(1),
    [anon_sym_extractor] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_constructor] = ACTIONS(1),
    [anon_sym_infallible] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_primitive] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_pure] = ACTIONS(1),
    [anon_sym_partial] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_if_DASHlet] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [sym_const_sym] = ACTIONS(1),
    [aux_sym_integer_token1] = ACTIONS(1),
    [aux_sym_integer_token2] = ACTIONS(1),
    [aux_sym_integer_token3] = ACTIONS(1),
    [aux_sym_integer_token4] = ACTIONS(1),
    [anon_sym_POUNDt] = ACTIONS(1),
    [anon_sym_POUNDf] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(140),
    [sym_defn] = STATE(80),
    [sym_line_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(61),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(12), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(17), 1,
      anon_sym__,
    ACTIONS(20), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      sym_const_sym,
    ACTIONS(26), 1,
      aux_sym_integer_token1,
    STATE(35), 1,
      sym_pattern,
    STATE(36), 1,
      sym_pattern_arg,
    ACTIONS(32), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(2), 2,
      sym_line_comment,
      aux_sym_pattern_repeat2,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(29), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [48] = 15,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(3), 1,
      sym_line_comment,
    STATE(4), 1,
      aux_sym_pattern_repeat2,
    STATE(35), 1,
      sym_pattern,
    STATE(36), 1,
      sym_pattern_arg,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [98] = 15,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_pattern_repeat2,
    STATE(4), 1,
      sym_line_comment,
    STATE(35), 1,
      sym_pattern,
    STATE(36), 1,
      sym_pattern_arg,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [148] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(5), 1,
      sym_line_comment,
    STATE(20), 1,
      aux_sym_rule_repeat1,
    STATE(46), 1,
      sym_condition,
    STATE(133), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    STATE(47), 2,
      sym_if_let,
      sym_if,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [191] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_line_comment,
    STATE(7), 1,
      aux_sym_rule_repeat1,
    STATE(46), 1,
      sym_condition,
    STATE(133), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    STATE(47), 2,
      sym_if_let,
      sym_if,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [234] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(7), 1,
      sym_line_comment,
    STATE(20), 1,
      aux_sym_rule_repeat1,
    STATE(46), 1,
      sym_condition,
    STATE(103), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    STATE(47), 2,
      sym_if_let,
      sym_if,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [277] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(5), 1,
      aux_sym_rule_repeat1,
    STATE(8), 1,
      sym_line_comment,
    STATE(46), 1,
      sym_condition,
    STATE(123), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    STATE(47), 2,
      sym_if_let,
      sym_if,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [320] = 12,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    ACTIONS(67), 1,
      anon_sym__,
    ACTIONS(70), 1,
      sym_const_sym,
    ACTIONS(73), 1,
      aux_sym_integer_token1,
    STATE(42), 1,
      sym_pattern,
    ACTIONS(79), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(9), 2,
      sym_line_comment,
      aux_sym_pattern_repeat1,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(76), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [362] = 13,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(10), 1,
      sym_line_comment,
    STATE(12), 1,
      aux_sym_pattern_repeat1,
    STATE(42), 1,
      sym_pattern,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [406] = 14,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(8), 1,
      sym_pattern,
    STATE(11), 1,
      sym_line_comment,
    STATE(21), 1,
      sym_priority,
    STATE(25), 1,
      sym_boolean,
    STATE(45), 1,
      sym_integer,
    STATE(127), 1,
      sym_rule,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [452] = 13,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      aux_sym_pattern_repeat1,
    STATE(12), 1,
      sym_line_comment,
    STATE(42), 1,
      sym_pattern,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [496] = 10,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    ACTIONS(90), 1,
      aux_sym_integer_token1,
    STATE(43), 1,
      sym_expression,
    ACTIONS(82), 2,
      sym_identifier,
      sym_const_sym,
    ACTIONS(96), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(13), 2,
      sym_line_comment,
      aux_sym_expression_repeat2,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(93), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [533] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym_line_comment,
    STATE(15), 1,
      aux_sym_expression_repeat2,
    STATE(43), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [572] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      aux_sym_expression_repeat2,
    STATE(15), 1,
      sym_line_comment,
    STATE(43), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [611] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(16), 1,
      sym_line_comment,
    STATE(105), 1,
      sym_pattern,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [649] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(17), 1,
      sym_line_comment,
    STATE(120), 1,
      sym_pattern,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [687] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(18), 1,
      sym_line_comment,
    STATE(23), 1,
      sym_pattern,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [725] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(19), 1,
      sym_line_comment,
    STATE(32), 1,
      sym_pattern,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [763] = 7,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    ACTIONS(110), 1,
      aux_sym_integer_token1,
    STATE(46), 1,
      sym_condition,
    STATE(20), 2,
      sym_line_comment,
      aux_sym_rule_repeat1,
    STATE(47), 2,
      sym_if_let,
      sym_if,
    ACTIONS(105), 7,
      sym_identifier,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [793] = 11,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym__,
    ACTIONS(45), 1,
      sym_const_sym,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    STATE(6), 1,
      sym_pattern,
    STATE(21), 1,
      sym_line_comment,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    STATE(25), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [831] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(116), 1,
      anon_sym_AT,
    STATE(22), 1,
      sym_line_comment,
    ACTIONS(112), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(114), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [857] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(23), 1,
      sym_line_comment,
    ACTIONS(118), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(120), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [880] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(122), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(124), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [903] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(25), 1,
      sym_line_comment,
    ACTIONS(112), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(114), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [926] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(26), 1,
      sym_line_comment,
    ACTIONS(126), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(128), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [949] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_line_comment,
    STATE(129), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [982] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(130), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(132), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1005] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_expression,
    STATE(29), 1,
      sym_line_comment,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1038] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      sym_line_comment,
    ACTIONS(134), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(136), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1061] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(31), 1,
      sym_line_comment,
    ACTIONS(138), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(140), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1084] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_line_comment,
    STATE(112), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1117] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_line_comment,
    STATE(139), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1150] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_line_comment,
    STATE(137), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1183] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(35), 1,
      sym_line_comment,
    ACTIONS(142), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(144), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1206] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      sym_line_comment,
    ACTIONS(146), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(148), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1229] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      sym_line_comment,
    ACTIONS(150), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(152), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1252] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      sym_line_comment,
    ACTIONS(154), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(156), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1275] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      sym_line_comment,
    ACTIONS(158), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(160), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1298] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(40), 1,
      sym_line_comment,
    ACTIONS(162), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(164), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1321] = 9,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      aux_sym_integer_token1,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(41), 1,
      sym_line_comment,
    STATE(116), 1,
      sym_expression,
    ACTIONS(51), 2,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
    ACTIONS(55), 2,
      sym_identifier,
      sym_const_sym,
    STATE(38), 2,
      sym_integer,
      sym_boolean,
    ACTIONS(49), 3,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
  [1354] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(42), 1,
      sym_line_comment,
    ACTIONS(166), 3,
      anon_sym__,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(168), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1376] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(172), 1,
      aux_sym_integer_token1,
    STATE(43), 1,
      sym_line_comment,
    ACTIONS(170), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1397] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(176), 1,
      aux_sym_integer_token1,
    STATE(44), 1,
      sym_line_comment,
    ACTIONS(174), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1418] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(184), 1,
      anon_sym__,
    STATE(45), 1,
      sym_line_comment,
    ACTIONS(178), 2,
      sym_identifier,
      aux_sym_integer_token1,
    ACTIONS(181), 7,
      anon_sym_LPAREN,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1441] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(188), 1,
      aux_sym_integer_token1,
    STATE(46), 1,
      sym_line_comment,
    ACTIONS(186), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1461] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(192), 1,
      aux_sym_integer_token1,
    STATE(47), 1,
      sym_line_comment,
    ACTIONS(190), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1481] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(196), 1,
      aux_sym_integer_token1,
    STATE(48), 1,
      sym_line_comment,
    ACTIONS(194), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1501] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(200), 1,
      aux_sym_integer_token1,
    STATE(49), 1,
      sym_line_comment,
    ACTIONS(198), 8,
      anon_sym_LPAREN,
      sym_identifier,
      sym_const_sym,
      aux_sym_integer_token2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
      anon_sym_POUNDt,
      anon_sym_POUNDf,
  [1521] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(50), 1,
      sym_line_comment,
    STATE(67), 1,
      aux_sym_decl_repeat1,
    STATE(127), 1,
      sym_decl,
    ACTIONS(204), 2,
      anon_sym_pure,
      anon_sym_partial,
  [1541] = 7,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(206), 1,
      anon_sym_type,
    ACTIONS(208), 1,
      anon_sym_decl,
    ACTIONS(210), 1,
      anon_sym_rule,
    ACTIONS(212), 1,
      anon_sym_extractor,
    ACTIONS(214), 1,
      anon_sym_extern,
    STATE(51), 1,
      sym_line_comment,
  [1563] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_line_comment,
    STATE(59), 1,
      aux_sym_decl_repeat2,
    STATE(78), 1,
      sym_type,
  [1582] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_line_comment,
    STATE(58), 1,
      aux_sym_enum_repeat1,
    STATE(84), 1,
      sym_enum_variant,
  [1601] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(224), 1,
      sym_identifier,
    ACTIONS(226), 1,
      anon_sym_if_DASHlet,
    ACTIONS(228), 1,
      anon_sym_if,
    ACTIONS(230), 1,
      anon_sym_let,
    STATE(54), 1,
      sym_line_comment,
  [1620] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      sym_line_comment,
    STATE(56), 1,
      aux_sym_decl_repeat2,
    STATE(78), 1,
      sym_type,
  [1639] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(234), 1,
      sym_identifier,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_type,
    STATE(56), 2,
      sym_line_comment,
      aux_sym_decl_repeat2,
  [1656] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(239), 1,
      anon_sym_LPAREN,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      sym_line_comment,
    STATE(66), 1,
      aux_sym_expression_repeat1,
    STATE(96), 1,
      sym_let_binding,
  [1675] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      sym_line_comment,
    STATE(65), 1,
      aux_sym_enum_repeat1,
    STATE(84), 1,
      sym_enum_variant,
  [1694] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_decl_repeat2,
    STATE(59), 1,
      sym_line_comment,
    STATE(78), 1,
      sym_type,
  [1713] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_decl_repeat2,
    STATE(60), 1,
      sym_line_comment,
    STATE(78), 1,
      sym_type,
  [1732] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_line_comment,
    STATE(69), 1,
      aux_sym_source_file_repeat1,
    STATE(80), 1,
      sym_defn,
  [1751] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      sym_identifier,
    ACTIONS(251), 2,
      anon_sym_pure,
      anon_sym_partial,
    STATE(62), 2,
      sym_line_comment,
      aux_sym_decl_repeat1,
  [1766] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(254), 1,
      anon_sym_LPAREN,
    ACTIONS(256), 1,
      anon_sym_enum,
    STATE(63), 1,
      sym_line_comment,
    STATE(128), 2,
      sym_primitive,
      sym_enum,
  [1783] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_line_comment,
    STATE(68), 1,
      aux_sym_enum_variant_repeat1,
    STATE(93), 1,
      sym_enum_field,
  [1802] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(262), 1,
      anon_sym_LPAREN,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym_enum_variant,
    STATE(65), 2,
      sym_line_comment,
      aux_sym_enum_repeat1,
  [1819] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(239), 1,
      anon_sym_LPAREN,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_line_comment,
    STATE(71), 1,
      aux_sym_expression_repeat1,
    STATE(96), 1,
      sym_let_binding,
  [1838] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(269), 1,
      sym_identifier,
    STATE(62), 1,
      aux_sym_decl_repeat1,
    STATE(67), 1,
      sym_line_comment,
    ACTIONS(204), 2,
      anon_sym_pure,
      anon_sym_partial,
  [1855] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_line_comment,
    STATE(72), 1,
      aux_sym_enum_variant_repeat1,
    STATE(93), 1,
      sym_enum_field,
  [1874] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
    ACTIONS(275), 1,
      anon_sym_LPAREN,
    STATE(80), 1,
      sym_defn,
    STATE(69), 2,
      sym_line_comment,
      aux_sym_source_file_repeat1,
  [1891] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(278), 1,
      anon_sym_extractor,
    ACTIONS(280), 1,
      anon_sym_constructor,
    ACTIONS(282), 1,
      anon_sym_const,
    STATE(70), 1,
      sym_line_comment,
    STATE(127), 1,
      sym_extern,
  [1910] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(284), 1,
      anon_sym_LPAREN,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_let_binding,
    STATE(71), 2,
      sym_line_comment,
      aux_sym_expression_repeat1,
  [1927] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(289), 1,
      anon_sym_LPAREN,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_enum_field,
    STATE(72), 2,
      sym_line_comment,
      aux_sym_enum_variant_repeat1,
  [1944] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(294), 1,
      sym_identifier,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    STATE(73), 2,
      sym_line_comment,
      aux_sym_extractor_repeat1,
  [1958] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
    ACTIONS(301), 1,
      anon_sym_extern,
    STATE(74), 1,
      sym_line_comment,
    STATE(106), 1,
      sym_type_value,
  [1974] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(303), 1,
      sym_identifier,
    ACTIONS(305), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym_extractor_repeat1,
  [1990] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(76), 1,
      sym_line_comment,
    ACTIONS(307), 3,
      anon_sym_pure,
      anon_sym_partial,
      sym_identifier,
  [2002] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(303), 1,
      sym_identifier,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_extractor_repeat1,
    STATE(77), 1,
      sym_line_comment,
  [2018] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(78), 1,
      sym_line_comment,
    ACTIONS(311), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2029] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(79), 1,
      sym_line_comment,
    STATE(131), 1,
      sym_type,
  [2042] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(80), 1,
      sym_line_comment,
    ACTIONS(313), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [2053] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(81), 1,
      sym_line_comment,
    STATE(107), 1,
      sym_type,
  [2066] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(315), 1,
      sym_identifier,
    STATE(82), 1,
      sym_line_comment,
    STATE(127), 1,
      sym_type_decl,
  [2079] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(83), 1,
      sym_line_comment,
    ACTIONS(317), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2090] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      sym_line_comment,
    ACTIONS(319), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2101] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(85), 1,
      sym_line_comment,
    STATE(138), 1,
      sym_type,
  [2114] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(321), 1,
      anon_sym_LPAREN,
    STATE(86), 1,
      sym_line_comment,
    STATE(127), 1,
      sym_extractor,
  [2127] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(87), 1,
      sym_line_comment,
    STATE(110), 1,
      sym_type,
  [2140] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(226), 1,
      anon_sym_if_DASHlet,
    ACTIONS(228), 1,
      anon_sym_if,
    STATE(88), 1,
      sym_line_comment,
  [2153] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(89), 1,
      sym_line_comment,
    ACTIONS(323), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2164] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(33), 1,
      sym_type,
    STATE(90), 1,
      sym_line_comment,
  [2177] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(91), 1,
      sym_line_comment,
    ACTIONS(325), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2188] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(224), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_let,
    STATE(92), 1,
      sym_line_comment,
  [2201] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(93), 1,
      sym_line_comment,
    ACTIONS(327), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2212] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(94), 1,
      sym_line_comment,
    ACTIONS(329), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2223] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(331), 1,
      sym_identifier,
    ACTIONS(333), 1,
      anon_sym_and,
    STATE(95), 1,
      sym_line_comment,
  [2236] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(96), 1,
      sym_line_comment,
    ACTIONS(335), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [2247] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(337), 1,
      sym_identifier,
    ACTIONS(339), 1,
      anon_sym_infallible,
    STATE(97), 1,
      sym_line_comment,
  [2260] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(98), 1,
      sym_line_comment,
    STATE(126), 1,
      sym_type,
  [2273] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(99), 1,
      sym_line_comment,
    ACTIONS(341), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2284] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      sym_line_comment,
    STATE(102), 1,
      sym_type_value,
  [2297] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    STATE(101), 1,
      sym_line_comment,
    ACTIONS(343), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [2308] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(345), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_line_comment,
  [2318] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      sym_line_comment,
  [2328] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(349), 1,
      anon_sym_LPAREN,
    STATE(104), 1,
      sym_line_comment,
  [2338] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(351), 1,
      anon_sym_RPAREN,
    STATE(105), 1,
      sym_line_comment,
  [2348] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(353), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      sym_line_comment,
  [2358] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(355), 1,
      anon_sym_RPAREN,
    STATE(107), 1,
      sym_line_comment,
  [2368] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(357), 1,
      anon_sym_RPAREN,
    STATE(108), 1,
      sym_line_comment,
  [2378] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(359), 1,
      sym_const_sym,
    STATE(109), 1,
      sym_line_comment,
  [2388] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(361), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      sym_line_comment,
  [2398] = 3,
    ACTIONS(363), 1,
      anon_sym_SEMI,
    ACTIONS(365), 1,
      aux_sym_line_comment_token1,
    STATE(111), 1,
      sym_line_comment,
  [2408] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(367), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      sym_line_comment,
  [2418] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(369), 1,
      sym_identifier,
    STATE(113), 1,
      sym_line_comment,
  [2428] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(371), 1,
      sym_identifier,
    STATE(114), 1,
      sym_line_comment,
  [2438] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(373), 1,
      sym_identifier,
    STATE(115), 1,
      sym_line_comment,
  [2448] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(375), 1,
      anon_sym_RPAREN,
    STATE(116), 1,
      sym_line_comment,
  [2458] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(377), 1,
      sym_identifier,
    STATE(117), 1,
      sym_line_comment,
  [2468] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(379), 1,
      sym_identifier,
    STATE(118), 1,
      sym_line_comment,
  [2478] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(381), 1,
      anon_sym_LPAREN,
    STATE(119), 1,
      sym_line_comment,
  [2488] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(383), 1,
      anon_sym_RPAREN,
    STATE(120), 1,
      sym_line_comment,
  [2498] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
    STATE(121), 1,
      sym_line_comment,
  [2508] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(387), 1,
      sym_identifier,
    STATE(122), 1,
      sym_line_comment,
  [2518] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(389), 1,
      anon_sym_RPAREN,
    STATE(123), 1,
      sym_line_comment,
  [2528] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(391), 1,
      sym_identifier,
    STATE(124), 1,
      sym_line_comment,
  [2538] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(393), 1,
      anon_sym_primitive,
    STATE(125), 1,
      sym_line_comment,
  [2548] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(395), 1,
      anon_sym_RPAREN,
    STATE(126), 1,
      sym_line_comment,
  [2558] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(397), 1,
      anon_sym_RPAREN,
    STATE(127), 1,
      sym_line_comment,
  [2568] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(399), 1,
      anon_sym_RPAREN,
    STATE(128), 1,
      sym_line_comment,
  [2578] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(401), 1,
      anon_sym_RPAREN,
    STATE(129), 1,
      sym_line_comment,
  [2588] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(403), 1,
      anon_sym_LPAREN,
    STATE(130), 1,
      sym_line_comment,
  [2598] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(405), 1,
      anon_sym_RPAREN,
    STATE(131), 1,
      sym_line_comment,
  [2608] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(407), 1,
      anon_sym_RPAREN,
    STATE(132), 1,
      sym_line_comment,
  [2618] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(409), 1,
      anon_sym_RPAREN,
    STATE(133), 1,
      sym_line_comment,
  [2628] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(411), 1,
      sym_identifier,
    STATE(134), 1,
      sym_line_comment,
  [2638] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(413), 1,
      sym_identifier,
    STATE(135), 1,
      sym_line_comment,
  [2648] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(415), 1,
      sym_identifier,
    STATE(136), 1,
      sym_line_comment,
  [2658] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(417), 1,
      anon_sym_RPAREN,
    STATE(137), 1,
      sym_line_comment,
  [2668] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(419), 1,
      anon_sym_RPAREN,
    STATE(138), 1,
      sym_line_comment,
  [2678] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(421), 1,
      anon_sym_RPAREN,
    STATE(139), 1,
      sym_line_comment,
  [2688] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(423), 1,
      ts_builtin_sym_end,
    STATE(140), 1,
      sym_line_comment,
  [2698] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(425), 1,
      anon_sym_RPAREN,
    STATE(141), 1,
      sym_line_comment,
  [2708] = 1,
    ACTIONS(427), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 148,
  [SMALL_STATE(6)] = 191,
  [SMALL_STATE(7)] = 234,
  [SMALL_STATE(8)] = 277,
  [SMALL_STATE(9)] = 320,
  [SMALL_STATE(10)] = 362,
  [SMALL_STATE(11)] = 406,
  [SMALL_STATE(12)] = 452,
  [SMALL_STATE(13)] = 496,
  [SMALL_STATE(14)] = 533,
  [SMALL_STATE(15)] = 572,
  [SMALL_STATE(16)] = 611,
  [SMALL_STATE(17)] = 649,
  [SMALL_STATE(18)] = 687,
  [SMALL_STATE(19)] = 725,
  [SMALL_STATE(20)] = 763,
  [SMALL_STATE(21)] = 793,
  [SMALL_STATE(22)] = 831,
  [SMALL_STATE(23)] = 857,
  [SMALL_STATE(24)] = 880,
  [SMALL_STATE(25)] = 903,
  [SMALL_STATE(26)] = 926,
  [SMALL_STATE(27)] = 949,
  [SMALL_STATE(28)] = 982,
  [SMALL_STATE(29)] = 1005,
  [SMALL_STATE(30)] = 1038,
  [SMALL_STATE(31)] = 1061,
  [SMALL_STATE(32)] = 1084,
  [SMALL_STATE(33)] = 1117,
  [SMALL_STATE(34)] = 1150,
  [SMALL_STATE(35)] = 1183,
  [SMALL_STATE(36)] = 1206,
  [SMALL_STATE(37)] = 1229,
  [SMALL_STATE(38)] = 1252,
  [SMALL_STATE(39)] = 1275,
  [SMALL_STATE(40)] = 1298,
  [SMALL_STATE(41)] = 1321,
  [SMALL_STATE(42)] = 1354,
  [SMALL_STATE(43)] = 1376,
  [SMALL_STATE(44)] = 1397,
  [SMALL_STATE(45)] = 1418,
  [SMALL_STATE(46)] = 1441,
  [SMALL_STATE(47)] = 1461,
  [SMALL_STATE(48)] = 1481,
  [SMALL_STATE(49)] = 1501,
  [SMALL_STATE(50)] = 1521,
  [SMALL_STATE(51)] = 1541,
  [SMALL_STATE(52)] = 1563,
  [SMALL_STATE(53)] = 1582,
  [SMALL_STATE(54)] = 1601,
  [SMALL_STATE(55)] = 1620,
  [SMALL_STATE(56)] = 1639,
  [SMALL_STATE(57)] = 1656,
  [SMALL_STATE(58)] = 1675,
  [SMALL_STATE(59)] = 1694,
  [SMALL_STATE(60)] = 1713,
  [SMALL_STATE(61)] = 1732,
  [SMALL_STATE(62)] = 1751,
  [SMALL_STATE(63)] = 1766,
  [SMALL_STATE(64)] = 1783,
  [SMALL_STATE(65)] = 1802,
  [SMALL_STATE(66)] = 1819,
  [SMALL_STATE(67)] = 1838,
  [SMALL_STATE(68)] = 1855,
  [SMALL_STATE(69)] = 1874,
  [SMALL_STATE(70)] = 1891,
  [SMALL_STATE(71)] = 1910,
  [SMALL_STATE(72)] = 1927,
  [SMALL_STATE(73)] = 1944,
  [SMALL_STATE(74)] = 1958,
  [SMALL_STATE(75)] = 1974,
  [SMALL_STATE(76)] = 1990,
  [SMALL_STATE(77)] = 2002,
  [SMALL_STATE(78)] = 2018,
  [SMALL_STATE(79)] = 2029,
  [SMALL_STATE(80)] = 2042,
  [SMALL_STATE(81)] = 2053,
  [SMALL_STATE(82)] = 2066,
  [SMALL_STATE(83)] = 2079,
  [SMALL_STATE(84)] = 2090,
  [SMALL_STATE(85)] = 2101,
  [SMALL_STATE(86)] = 2114,
  [SMALL_STATE(87)] = 2127,
  [SMALL_STATE(88)] = 2140,
  [SMALL_STATE(89)] = 2153,
  [SMALL_STATE(90)] = 2164,
  [SMALL_STATE(91)] = 2177,
  [SMALL_STATE(92)] = 2188,
  [SMALL_STATE(93)] = 2201,
  [SMALL_STATE(94)] = 2212,
  [SMALL_STATE(95)] = 2223,
  [SMALL_STATE(96)] = 2236,
  [SMALL_STATE(97)] = 2247,
  [SMALL_STATE(98)] = 2260,
  [SMALL_STATE(99)] = 2273,
  [SMALL_STATE(100)] = 2284,
  [SMALL_STATE(101)] = 2297,
  [SMALL_STATE(102)] = 2308,
  [SMALL_STATE(103)] = 2318,
  [SMALL_STATE(104)] = 2328,
  [SMALL_STATE(105)] = 2338,
  [SMALL_STATE(106)] = 2348,
  [SMALL_STATE(107)] = 2358,
  [SMALL_STATE(108)] = 2368,
  [SMALL_STATE(109)] = 2378,
  [SMALL_STATE(110)] = 2388,
  [SMALL_STATE(111)] = 2398,
  [SMALL_STATE(112)] = 2408,
  [SMALL_STATE(113)] = 2418,
  [SMALL_STATE(114)] = 2428,
  [SMALL_STATE(115)] = 2438,
  [SMALL_STATE(116)] = 2448,
  [SMALL_STATE(117)] = 2458,
  [SMALL_STATE(118)] = 2468,
  [SMALL_STATE(119)] = 2478,
  [SMALL_STATE(120)] = 2488,
  [SMALL_STATE(121)] = 2498,
  [SMALL_STATE(122)] = 2508,
  [SMALL_STATE(123)] = 2518,
  [SMALL_STATE(124)] = 2528,
  [SMALL_STATE(125)] = 2538,
  [SMALL_STATE(126)] = 2548,
  [SMALL_STATE(127)] = 2558,
  [SMALL_STATE(128)] = 2568,
  [SMALL_STATE(129)] = 2578,
  [SMALL_STATE(130)] = 2588,
  [SMALL_STATE(131)] = 2598,
  [SMALL_STATE(132)] = 2608,
  [SMALL_STATE(133)] = 2618,
  [SMALL_STATE(134)] = 2628,
  [SMALL_STATE(135)] = 2638,
  [SMALL_STATE(136)] = 2648,
  [SMALL_STATE(137)] = 2658,
  [SMALL_STATE(138)] = 2668,
  [SMALL_STATE(139)] = 2678,
  [SMALL_STATE(140)] = 2688,
  [SMALL_STATE(141)] = 2698,
  [SMALL_STATE(142)] = 2708,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(22),
  [12] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(95),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(25),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(29),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(25),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(39),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(39),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 2), SHIFT_REPEAT(37),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(22),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(95),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(25),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(25),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(39),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(39),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(37),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(38),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(92),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(39),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(39),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(37),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2), SHIFT_REPEAT(88),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 4),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern_arg, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_arg, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 7),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 7),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 6),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 6),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern_arg, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_arg, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat2, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat2, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat2, 1),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat2, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_priority, 1), REDUCE(sym_pattern, 1),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_priority, 1), REDUCE(sym_pattern, 1),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_priority, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 1),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_let, 5),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_let, 5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 4),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 4),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 1),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decl_repeat2, 2), SHIFT_REPEAT(44),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decl_repeat2, 2),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_decl_repeat1, 2),
  [251] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_decl_repeat1, 2), SHIFT_REPEAT(76),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2), SHIFT_REPEAT(134),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(114),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_variant_repeat1, 2), SHIFT_REPEAT(122),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_variant_repeat1, 2),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extractor_repeat1, 2), SHIFT_REPEAT(99),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extractor_repeat1, 2),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_decl_repeat1, 1),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decl_repeat2, 1),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 1),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_field, 4),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 5),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_variant_repeat1, 1),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 3),
  [331] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [333] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 1),
  [337] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extractor_repeat1, 1),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 4),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 3),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extractor, 4),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 2),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 4),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 5),
  [363] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [365] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extractor, 5),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 4),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 6),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [405] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 4),
  [407] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 3),
  [409] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [423] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [425] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 3),
  [427] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_isle(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
